# Generated by Django 4.2.1 on 2023-05-25 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(1, message="Weight must be at least 1.0."),
                            django.core.validators.MaxValueValidator(1000, message="Weight cannot exceed 1000.0."),
                        ],
                    ),
                ),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "delivery_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_cargos",
                        to="location.location",
                    ),
                ),
                (
                    "pick_up_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pick_up_cargos",
                        to="location.location",
                    ),
                ),
            ],
        ),
    ]
