# Generated by Django 4.2.1 on 2023-05-25 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "unique_number",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Number must be in the format of number from 1000 to 9999 + random uppercase letter from the English alphabet at the end.",
                                regex="^[1-9][0-9]{3}[A-Z]$",
                            )
                        ],
                    ),
                ),
                (
                    "load_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(1, message="Weight must be at least 1.0."),
                            django.core.validators.MaxValueValidator(1000, message="Weight cannot exceed 1000.0."),
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "current_location",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="location.location"),
                ),
            ],
        ),
    ]
