# Generated by Django 4.2.1 on 2023-05-25 10:44
from random import randint

from django.db import migrations

CARS_NUMBER = 20


def prefill_cars(apps, schema_editor):
    """Pre-fill the database with a specified number of cars."""
    Car = apps.get_model("car", "Car")
    Location = apps.get_model("location", "Location")

    locations_count = Location.objects.count()
    locations_list = Location.objects.all()

    cars = []
    for i in range(CARS_NUMBER):
        random_index = randint(0, locations_count - 1)
        cars.append(
            Car(
                unique_number=f"{1000 + i}T",
                current_location=locations_list[random_index],
                load_capacity=randint(1, 1000),
            )
        )
    Car.objects.bulk_create(cars)


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0001_initial"),
        ("location", "0003_import_uszips_csv"),
    ]

    operations = [migrations.RunPython(prefill_cars)]
