# Generated by Django 4.2.1 on 2023-05-25 10:44
from random import sample, randint

from django.db import migrations
from django.db.models import Max

CARS_NUMBER = 20


def prefill_cars(apps, schema_editor):
    Car = apps.get_model("car", "Car")
    Location = apps.get_model("location", "Location")

    pk_max = Location.objects.all().aggregate(pk_max=Max("pk"))["pk_max"]
    random_pk_list = sample(range(1, pk_max + 1), 1000)
    random_locations = Location.objects.filter(pk__in=random_pk_list)[:CARS_NUMBER]

    cars = []
    for i in range(CARS_NUMBER):
        cars.append(
            Car(
                unique_number=f"{1000 + i}T",
                current_location=random_locations[i],
                load_capacity=randint(1, 1000),
            )
        )
    Car.objects.bulk_create(cars)


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [migrations.RunPython(prefill_cars)]
